'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { project, toDrawing, millerY, WIDTH, HEIGHT, LAT_MIN, LAT_MAX, LON_MIN, LON_MAX } = require('../server/lib/geo');
const { build } = require('../scripts/make-worldmap');
const { buildOverview } = require('../server/lib/overview');
const { P, freshStore } = require('./helpers');

const close = (a, b, eps = 1e-9) => Math.abs(a - b) < eps;

// ---------------------------------------------------------------- the projection
test('the map is the whole world east to west, and its corners are the corners of the box', () => {
  assert.deepEqual(project(LAT_MAX, LON_MIN), { x: 0, y: 0 });
  const bottomRight = project(LAT_MIN, LON_MAX);
  assert.ok(close(bottomRight.x, 1) && close(bottomRight.y, 1));
  assert.ok(close(project(0, 0).x, 0.5), 'the prime meridian is in the middle');
  assert.equal(WIDTH, 1000);
  assert.ok(HEIGHT > 480 && HEIGHT < 520, `about 2:1, not ${WIDTH} x ${HEIGHT}`);
});

test('east is right and north is up, everywhere', () => {
  for (const lat of [-50, -20, 0, 30, 60, 80]) for (let lon = -170; lon < 170; lon += 20) {
    assert.ok(project(lat, lon + 10).x > project(lat, lon).x, `${lat}, ${lon}`);
    assert.ok(project(lat + 4, lon).y < project(lat, lon).y, `${lat}, ${lon}`);
  }
  assert.ok(millerY(60) > millerY(30) && millerY(30) > millerY(0), 'Miller stretches toward the poles');
});

test('a place outside the map\'s latitudes is pinned to its edge rather than dropped off it', () => {
  assert.equal(project(-89, 10).y, 1);
  assert.equal(project(89, 10).y, 0);
  assert.equal(project(10, 999).x, 1);
  assert.equal(project(10, -999).x, 0);
});

test('the marker position and the drawing position are the same place', () => {
  const p = project(35.7, 139.7), d = toDrawing(35.7, 139.7);
  assert.ok(close(d.x, p.x * WIDTH) && close(d.y, p.y * HEIGHT));
});

// ---------------------------------------------------------------- the outline
test('the committed outline is exactly what the generator produces from the Natural Earth source', () => {
  const file = path.join(__dirname, '..', 'web', 'app', 'worldmap.js');
  assert.equal(fs.readFileSync(file, 'utf8'), build().text, 'web/app/worldmap.js is out of date: run npm run worldmap');
});

test('the outline is a single path over the whole box, drops Antarctica and credits its source', () => {
  const { text, polygons } = build();
  assert.match(text, /^\/\* Generated by scripts\/make-worldmap\.js from Natural Earth 1:110m land \(public domain/);
  const map = new Function('window', `${text}; return window.LAB_WORLDMAP;`)({});
  assert.equal(map.width, WIDTH);
  assert.equal(map.height, HEIGHT);
  assert.match(map.d, /^M[\d.,L-]+Z/);
  assert.ok(map.d.length > 20000 && map.d.length < 90000, `${map.d.length} characters`);
  assert.ok(polygons > 100 && polygons < 127, `${polygons} land outlines kept of 127: Antarctica and nothing else is dropped`);
  const nums = map.d.match(/-?\d+(\.\d+)?/g).map(Number);
  assert.ok(Math.min(...nums) >= -1 && Math.max(...nums) <= WIDTH + 1, 'every point is inside the box');
});

// ---------------------------------------------------------------- the pools are on land
// Ray casting against the source polygons, in longitude and latitude: is this place on land?
function onLand(lat, lon) {
  const geo = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'scripts', 'data', 'ne_110m_land.geojson'), 'utf8'));
  const polys = geo.features.flatMap((f) => (f.geometry.type === 'Polygon' ? [f.geometry.coordinates] : f.geometry.coordinates));
  const inside = (ring) => { let c = false; for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) { const [xi, yi] = ring[i], [xj, yj] = ring[j]; if ((yi > lat) !== (yj > lat) && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) c = !c; } return c; };
  return polys.some((rings) => inside(rings[0]) && !rings.slice(1).some(inside));
}

test('the pools whose city the outline resolves are on land, so a dot never sits in the sea by mistake', () => {
  const { data } = { data: freshStore().data() };
  const known = { [P.eus]: 'Virginia', [P.weuAmd]: 'the Netherlands', [P.jpe]: 'Honshu', [P.brs]: 'Sao Paulo' };
  for (const [id, where] of Object.entries(known)) {
    const pool = data.poolById[id];
    assert.ok(onLand(pool.lat, pool.lon), `${id} (${where}) at ${pool.lat}, ${pool.lon} is not on land in the outline`);
  }
  assert.ok(!onLand(0, -150), 'and the check does say no to the middle of the Pacific');
});

// ---------------------------------------------------------------- what the API gives the map
test('each region carries the capacity-weighted centre of its pools, and where that is on the map', () => {
  const store = freshStore();
  const o = buildOverview(store, {});
  const byGeo = {};
  for (const a of store.all()) (byGeo[a.ctx.pool.geo] ||= []).push(a.ctx.pool);
  for (const r of o.regions) {
    const pools = byGeo[r.key];
    const w = pools.reduce((s, p) => s + p.capacity_units, 0);
    const lat = pools.reduce((s, p) => s + p.lat * p.capacity_units, 0) / w;
    const lon = pools.reduce((s, p) => s + p.lon * p.capacity_units, 0) / w;
    assert.ok(Math.abs(r.lat - lat) < 0.006 && Math.abs(r.lon - lon) < 0.006, `${r.key}: ${r.lat}, ${r.lon} against ${lat}, ${lon}`);
    assert.deepEqual(r.map, project(lat, lon));
    assert.ok(r.map.x >= 0 && r.map.x <= 1 && r.map.y >= 0 && r.map.y <= 1);
  }
  const by = Object.fromEntries(o.regions.map((r) => [r.key, r]));
  assert.deepEqual(by['north-america'].map, project(36.7, -78.4), 'one pool: the dot is on the pool');
  assert.deepEqual(by.europe.map, project(52.4, 4.9), 'two pools in one city: the dot is on the city');
  const apac = by['asia-pacific'];
  assert.ok(apac.lon > 103.8 && apac.lon < 139.7 && apac.lat > 1.3 && apac.lat < 35.7, 'between Singapore and Tokyo');
  assert.ok(Math.abs(apac.lon - 103.8) < Math.abs(apac.lon - 139.7), 'nearer Singapore, which holds twice the capacity');
});

test('the regions do not sit on top of one another on the map', () => {
  const o = buildOverview(freshStore(), {});
  for (let i = 0; i < o.regions.length; i++) for (let j = i + 1; j < o.regions.length; j++) {
    const a = o.regions[i].map, b = o.regions[j].map;
    assert.ok(Math.hypot((a.x - b.x) * WIDTH, (a.y - b.y) * HEIGHT) > 120, `${o.regions[i].key} and ${o.regions[j].key}`);
  }
});

test('filtering to one region leaves only that region on the map', () => {
  const o = buildOverview(freshStore(), { region: 'europe' });
  assert.deepEqual(o.regions.map((r) => r.key), ['europe']);
  assert.deepEqual(o.regions[0].map, project(52.4, 4.9));
});
