'use strict';
/*
 * Writes test/fixtures/planning-golden.json: what the planning layer produces today, so a refactor of how it is built can
 * prove it moved nothing. For every pool it records each planning accessor (the forecast paths, the pipeline, the dated
 * adds, capacity as supply lands) at a spread of weeks, the plan that comes out of them, and the same for a few what-if
 * overrides. `test/contracts.test.js` compares the engine against this file.
 *
 * Regenerate it only when a change to the numbers is intended and understood: `node scripts/make-golden.js`.
 * `--full <file>` also writes every accessor at every week (for a one-off old-versus-new comparison).
 */

const fs = require('node:fs');
const path = require('node:path');
const { loadRaw, indexData } = require('../server/lib/data');
const { buildContext } = require('../server/lib/context');
const { assessPool } = require('../server/lib/verdict');

const ROOT = path.resolve(__dirname, '..');
const ACCESSORS = ['p50At', 'upperAt', 'pipelineAt', 'demandBase', 'knownAddsAt', 'seasonalSpikeAt', 'planDemandAt', 'usableAt', 'spreadAt', 'priorUpperAt', 'priorSpreadAt'];
const SAMPLE_WEEKS = [0, 1, 2, 4, 8, 13, 18, 26, 39, 52, 78, 104];
const OVERRIDES = [{}, { growth_pts_per_week: 1.5 }, { demand_scale: 1.15 }, { conversion_factor: 1.35 }, { lead_time_weeks: 8 }, { floor_pct: 0.9 }];
const r6 = (x) => (Number.isFinite(x) ? +x.toFixed(6) : x);

function planOf(v) {
  return {
    state: v.state, priority: v.priority, headline: v.headline, lead_weeks: v.lead.weeks,
    order: { needed: v.order.needed, quantity_cu: v.order.quantity_cu, cost_usd: v.order.cost_usd, cover_until_week: v.order.cover_until_week, components: v.order.components.map((c) => [c.label, r6(c.value)]) },
    dates: v.dates, capacity: Object.fromEntries(Object.entries(v.capacity).map(([k, x]) => [k, r6(x)])),
    horizons: v.horizons.map((h) => h.status), funnels: v.trace.map((t) => [t.number, t.status, t.severity]),
    reclaim: v.reclaim,
  };
}

function build(weeks) {
  const data = indexData(loadRaw(path.join(ROOT, 'data')));
  const out = { note: 'Generated by scripts/make-golden.js. Do not edit by hand.', as_of: data.as_of, weeks, pools: {} };
  for (const pool of data.pools) {
    const entry = { accessors: {}, prior_plan_demand: [], plans: [] };
    const ctx = buildContext(data, pool.pool_id);
    for (const name of ACCESSORS) entry.accessors[name] = weeks.map((h) => r6(ctx[name](h)));
    entry.prior_plan_demand = weeks.map((h) => r6(ctx.planDemandAt(h, { prior: true })));
    entry.plans = OVERRIDES.map((o) => ({ overrides: o, ...planOf(assessPool(data, pool.pool_id, o).verdict) }));
    out.pools[pool.pool_id] = entry;
  }
  return out;
}

if (require.main === module) {
  const dir = path.join(ROOT, 'test', 'fixtures');
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'planning-golden.json'), `${JSON.stringify(build(SAMPLE_WEEKS), null, 1)}\n`);
  console.log('golden: wrote test/fixtures/planning-golden.json');
  const i = process.argv.indexOf('--full');
  if (i > 0) {
    fs.writeFileSync(path.resolve(process.argv[i + 1]), JSON.stringify(build(Array.from({ length: 105 }, (_, h) => h))));
    console.log(`golden: wrote every week to ${process.argv[i + 1]}`);
  }
}

module.exports = { build, SAMPLE_WEEKS, ACCESSORS, OVERRIDES };
